import type { CollectibleItem } from "../../types";

// === Level 1 items ===
export const level1Items: CollectibleItem[] = [
  // Target items
  {
    id: "smetana_tub",
    name: "White Tub",
    script: "СМЕТАНА",
    description: "A plastic tub of something white and creamy.",
    isDecoy: false,
    color: "#FFFAF0",
  },
  {
    id: "kefir_bottle",
    name: "Tall Bottle",
    script: "КЕФИР",
    description: "A tall bottle of some fermented drink.",
    isDecoy: false,
    color: "#E8F5E9",
  },
  {
    id: "kolbasa_link",
    name: "Sausage Link",
    script: "КОЛБАСА",
    description: "A hefty link of cured meat.",
    isDecoy: false,
    color: "#C62828",
  },
  // Decoy items
  {
    id: "pickle_jar",
    name: "Pickle Jar",
    script: "ОГУРЦЫ",
    description: "A jar of pickled cucumbers.",
    isDecoy: true,
    color: "#4CAF50",
  },
  {
    id: "bread_loaf",
    name: "Bread Loaf",
    script: "БАТОН",
    description: "A round loaf of golden bread.",
    isDecoy: true,
    color: "#c4a882",
  },
  {
    id: "mystery_can",
    name: "Mystery Can",
    revealName: "Beetroot",
    script: "СВЁКЛА",
    description: "A dented grey tin. The label fell off. It's written in marker...",
    isDecoy: true,
    color: "#9E9E9E",
    pronunciation: "SVYOK-la",
    revealSpriteId: "beet_reveal",
    hints: [
      "I wonder what makes borscht that color...",
      "It's a root vegetable. Very purple. Think.",
      "I may have removed the label. For educational purposes.",
    ],
  },
  {
    id: "sunflower_seeds",
    name: "Seed Bag",
    script: "СЕМЕЧКИ",
    description: "A rustling bag of sunflower seeds.",
    isDecoy: true,
    color: "#FFC107",
  },
];

// === Level 2 items ===
export const level2Items: CollectibleItem[] = [
  // Targets
  {
    id: "moloko_carton",
    name: "Milk Carton",
    script: "МОЛОКО",
    description: "A white carton with a blue label.",
    isDecoy: false,
    color: "#ffffff",
  },
  {
    id: "chai_box",
    name: "Tea Box",
    script: "ЧАЙ",
    description: "An orange box with a leaf on it.",
    isDecoy: false,
    color: "#cc7733",
  },
  {
    id: "sakhar_bag",
    name: "Sugar Bag",
    script: "САХАР",
    description: "A white bag of something granular.",
    isDecoy: false,
    color: "#eeeeee",
  },
  // Decoys
  {
    id: "pickle_jar",
    name: "Pickle Jar",
    script: "ОГУРЦЫ",
    description: "A jar of pickled cucumbers.",
    isDecoy: true,
    color: "#4CAF50",
  },
  {
    id: "mystery_can",
    name: "Mystery Can",
    revealName: "Beans",
    script: "ГОРОШЕК",
    description: "A dented grey tin. The label fell off. It's written in marker...",
    isDecoy: true,
    color: "#9E9E9E",
    pronunciation: "ga-RO-shek",
    revealSpriteId: "pea_reveal",
    hints: [
      "Small. Green. Round. Like your attention span.",
      "They grow in pods, Chad. Pods.",
      "The label didn't fall off. I peeled it. You're learning.",
    ],
  },
  {
    id: "vodka_bottle",
    name: "Tall Frosted Bottle",
    script: "ВОДКА",
    description: "A frosted bottle with a red stripe label.",
    isDecoy: true,
    color: "#eeeeee",
  },
  {
    id: "konfeta_candy",
    name: "Purple Candy",
    script: "КОНФЕТА",
    description: "A wrapped candy with a gold stripe.",
    isDecoy: true,
    color: "#9944bb",
  },
];

// === Level 3 items ===
export const level3Items: CollectibleItem[] = [
  // Targets
  {
    id: "maslo_butter",
    name: "Butter Block",
    script: "МАСЛО",
    description: "A yellow block wrapped in foil.",
    isDecoy: false,
    color: "#ffcc44",
  },
  {
    id: "ryba_fish",
    name: "Fish",
    script: "РЫБА",
    description: "A blue-gray fish with fins and a tail.",
    isDecoy: false,
    color: "#88aacc",
  },
  {
    id: "kartoshka",
    name: "Potato",
    script: "КАРТОШКА",
    description: "A plain brown potato. No face. Just a potato.",
    isDecoy: false,
    color: "#c4944a",
  },
  {
    id: "hleb_rye",
    name: "Dark Bread",
    script: "ХЛЕБ",
    description: "A dark rye loaf with seeds on top.",
    isDecoy: false,
    color: "#5a3a1a",
  },
  // Decoys
  {
    id: "sunflower_seeds",
    name: "Seed Bag",
    script: "СЕМЕЧКИ",
    description: "A rustling bag of sunflower seeds.",
    isDecoy: true,
    color: "#FFC107",
  },
  {
    id: "smetana_tub",
    name: "White Tub",
    script: "СМЕТАНА",
    description: "A plastic tub of something white and creamy.",
    isDecoy: true,
    color: "#FFFAF0",
  },
  {
    id: "ogurtsy_cuke",
    name: "Cucumber",
    script: "ОГУРЦЫ",
    description: "A bumpy green cucumber.",
    isDecoy: true,
    color: "#449944",
  },
  {
    id: "bread_loaf",
    name: "Bread Loaf",
    script: "БАТОН",
    description: "A round loaf of golden bread.",
    isDecoy: true,
    color: "#c4a882",
  },
  {
    id: "mystery_can",
    name: "Mystery Can",
    script: "ТУШЁНКА",
    description: "A dented grey tin. The label fell off. It's written in marker...",
    isDecoy: true,
    color: "#9E9E9E",
    revealName: "Canned Stew",
    revealSpriteId: "tushyonka_reveal",
    pronunciation: "too-SHON-kah",
    hints: [
      "It's not a vegetable. It's not a fruit. It mooed once.",
      "Soldiers eat this. Campers eat this. You, apparently, cannot read this.",
      "I labeled it myself. With a marker. You're welcome.",
    ],
  },
];

// === Level 4 items ===
export const level4Items: CollectibleItem[] = [
  // Targets
  {
    id: "yabloko_apple",
    name: "Apple",
    script: "ЯБЛОКО",
    description: "A red apple with a green leaf.",
    isDecoy: false,
    color: "#cc2222",
  },
  {
    id: "syr_cheese",
    name: "Cheese Wedge",
    script: "СЫР",
    description: "A yellow wedge of cheese with holes.",
    isDecoy: false,
    color: "#ffcc44",
  },
  {
    id: "konfeta_candy",
    name: "Purple Candy",
    script: "КОНФЕТА",
    description: "A wrapped candy with a gold stripe.",
    isDecoy: false,
    color: "#9944bb",
  },
  // Decoys
  {
    id: "vodka_bottle",
    name: "Tall Frosted Bottle",
    script: "ВОДКА",
    description: "A frosted bottle with a red stripe label.",
    isDecoy: true,
    color: "#eeeeee",
  },
  {
    id: "maslo_butter",
    name: "Butter Block",
    script: "МАСЛО",
    description: "A yellow block wrapped in foil.",
    isDecoy: true,
    color: "#ffcc44",
  },
  {
    id: "moloko_carton",
    name: "Milk Carton",
    script: "МОЛОКО",
    description: "A white carton with a blue label.",
    isDecoy: true,
    color: "#ffffff",
  },
  {
    id: "kartoshka",
    name: "Potato",
    script: "КАРТОШКА",
    description: "A plain brown potato.",
    isDecoy: true,
    color: "#c4944a",
  },
  {
    id: "mystery_can",
    name: "Mystery Can",
    revealName: "Corn",
    script: "КУКУРУЗА",
    description: "A dented grey tin. The label fell off. It's written in marker...",
    isDecoy: true,
    color: "#9E9E9E",
    pronunciation: "ku-ku-RU-za",
    revealSpriteId: "corn_reveal",
    hints: [
      "Yellow. On a cob. Americans drown it in butter.",
      "It's the tall plant. With the husks. Come on.",
      "I put this can here on purpose. You will learn.",
    ],
  },
];

// === Level 5 items ===
export const level5Items: CollectibleItem[] = [
  // Targets
  {
    id: "tarelka_plate",
    name: "Plate",
    script: "ТАРЕЛКА",
    description: "A white ceramic plate with a blue rim.",
    isDecoy: false,
    color: "#e0e8f0",
  },
  {
    id: "lozhka_spoon",
    name: "Spoon",
    script: "ЛОЖКА",
    description: "A shiny metal spoon.",
    isDecoy: false,
    color: "#cccccc",
  },
  {
    id: "chashka_cup",
    name: "Cup",
    script: "ЧАШКА",
    description: "A ceramic cup. Probably for tea.",
    isDecoy: false,
    color: "#e0e8f0",
  },
  // Decoys
  {
    id: "podushka_pillow",
    name: "Pillow",
    script: "ПОДУШКА",
    description: "A fluffy white pillow. Not breakfast.",
    isDecoy: true,
    color: "#ffffff",
  },
  {
    id: "chasy_clock",
    name: "Clock",
    script: "ЧАСЫ",
    description: "A ticking wall clock.",
    isDecoy: true,
    color: "#eeeeee",
  },
  {
    id: "mylo_soap",
    name: "Soap",
    script: "МЫЛО",
    description: "A bar of purple soap.",
    isDecoy: true,
    color: "#9944bb",
  },
  {
    id: "pult_remote",
    name: "Remote",
    script: "ПУЛЬТ",
    description: "A TV remote control.",
    isDecoy: true,
    color: "#555555",
  },
  {
    id: "mystery_can",
    name: "Mystery Can",
    script: "СГУЩЁНКА",
    description: "A dented grey tin. The label fell off. It's written in marker...",
    isDecoy: true,
    color: "#9E9E9E",
    revealName: "Condensed Milk",
    revealSpriteId: "sgushchyonka_reveal",
    pronunciation: "sgoo-SHCHON-kah",
    hints: [
      "Sweet. Sticky. Every Soviet child's weakness.",
      "You boil it in the can and it turns into caramel. Focus.",
      "The suffix is the same as the last can. Pattern recognition, Chad.",
    ],
  },
];

// === Level 6 items ===
export const level6Items: CollectibleItem[] = [
  // Targets — inside shops
  {
    id: "syr_wheel",
    name: "Cheese Wheel",
    script: "СЫР",
    description: "A whole wheel of cheese with holes.",
    isDecoy: false,
    color: "#ffcc44",
  },
  {
    id: "ryba_smoked",
    name: "Smoked Fish",
    script: "РЫБА",
    description: "A golden-brown smoked fish.",
    isDecoy: false,
    color: "#cc7733",
  },
  {
    id: "slivki_jar",
    name: "Cream Jar",
    script: "СЛИВКИ",
    description: "A glass jar of thick cream.",
    isDecoy: false,
    color: "#fffff0",
  },
  {
    id: "grib_basket",
    name: "Mushroom Basket",
    script: "ГРИБ",
    description: "A basket of forest mushrooms.",
    isDecoy: false,
    color: "#cc9933",
  },
  // Decoys — scattered in shops and outdoors
  {
    id: "kolbasa_ring",
    name: "Sausage Ring",
    script: "КОЛБАСА",
    description: "A ring of dried sausage.",
    isDecoy: true,
    color: "#991111",
  },
  {
    id: "kvass_bottle",
    name: "Brown Bottle",
    script: "КВАС",
    description: "A brown bottle of something fizzy.",
    isDecoy: true,
    color: "#8B5E3C",
  },
  {
    id: "pickle_jar",
    name: "Pickle Jar",
    script: "ОГУРЦЫ",
    description: "A jar of pickled cucumbers.",
    isDecoy: true,
    color: "#4CAF50",
  },
  {
    id: "sunflower_seeds",
    name: "Seed Bag",
    script: "СЕМЕЧКИ",
    description: "A rustling bag of sunflower seeds.",
    isDecoy: true,
    color: "#FFC107",
  },
  {
    id: "mystery_can",
    name: "Mystery Can",
    script: "ШПРОТЫ",
    description: "A dented grey tin. The label fell off. It's written in marker...",
    isDecoy: true,
    color: "#9E9E9E",
    revealName: "Sprats",
    revealSpriteId: "shproty_reveal",
    pronunciation: "SHPROH-tih",
    hints: [
      "Small. Oily. Comes in a flat tin. Think seafood.",
      "It's the fancy appetizer at every Soviet New Year's table.",
      "Tiny fish. In oil. I literally cannot be more clear.",
    ],
  },
];

// === Level 7 items ===
export const level7Items: CollectibleItem[] = [
  // Targets — returning words in vertical city
  {
    id: "sveokla_beet",
    name: "Beetroot",
    script: "СВЁКЛА",
    description: "A dark purple-red beetroot with a stubby green top.",
    isDecoy: false,
    color: "#6B1F3A",
    pronunciation: "SVYOK-la",
  },
  {
    id: "smetana_tub",
    name: "White Tub",
    script: "СМЕТАНА",
    description: "A plastic tub of something white and creamy.",
    isDecoy: false,
    color: "#FFFAF0",
  },
  {
    id: "hleb_rye",
    name: "Dark Bread",
    script: "ХЛЕБ",
    description: "A dark rye loaf with seeds on top.",
    isDecoy: false,
    color: "#5a3a1a",
  },
  {
    id: "maslo_butter",
    name: "Butter Block",
    script: "МАСЛО",
    description: "A yellow block wrapped in foil.",
    isDecoy: false,
    color: "#ffcc44",
  },
  // Decoys
  {
    id: "pickle_jar",
    name: "Pickle Jar",
    script: "ОГУРЦЫ",
    description: "A jar of pickled cucumbers.",
    isDecoy: true,
    color: "#4CAF50",
  },
  {
    id: "sunflower_seeds",
    name: "Seed Bag",
    script: "СЕМЕЧКИ",
    description: "A rustling bag of sunflower seeds.",
    isDecoy: true,
    color: "#FFC107",
  },
  {
    id: "kvass_bottle",
    name: "Brown Bottle",
    script: "КВАС",
    description: "A brown bottle of something fizzy.",
    isDecoy: true,
    color: "#8B5E3C",
  },
  {
    id: "mystery_can",
    name: "Mystery Can",
    script: "АНАНАС",
    description: "A dented grey tin. The label fell off. It's written in marker...",
    isDecoy: true,
    color: "#9E9E9E",
    revealName: "Pineapple",
    revealSpriteId: "ananas_reveal",
    pronunciation: "ah-nah-NAHS",
    hints: [
      "This one doesn't grow in Belarus. Think tropical.",
      "It's yellow. It's spiky on the outside. It's sweet.",
      "The word is almost the same in every language. Come on.",
    ],
  },
];

// === Level 8 items ===
export const level8Items: CollectibleItem[] = [
  // Targets
  {
    id: "ukrop_bunch",
    name: "Green Bunch",
    script: "УКРОП",
    description: "A feathery bunch of bright green herbs.",
    isDecoy: false,
    color: "#4CAF50",
    pronunciation: "oo-KROP",
  },
  {
    id: "ryba_smoked",
    name: "Smoked Fish",
    script: "РЫБА",
    description: "A golden-brown smoked fish.",
    isDecoy: false,
    color: "#cc7733",
  },
  {
    id: "grib_basket",
    name: "Mushroom Basket",
    script: "ГРИБ",
    description: "A basket of forest mushrooms.",
    isDecoy: false,
    color: "#cc9933",
  },
  // Decoys
  {
    id: "kvass_bottle",
    name: "Brown Bottle",
    script: "КВАС",
    description: "A brown bottle of something fizzy.",
    isDecoy: true,
    color: "#8B5E3C",
  },
  {
    id: "kolbasa_ring",
    name: "Sausage Ring",
    script: "КОЛБАСА",
    description: "A ring of dried sausage.",
    isDecoy: true,
    color: "#991111",
  },
  {
    id: "pickle_jar",
    name: "Pickle Jar",
    script: "ОГУРЦЫ",
    description: "A jar of pickled cucumbers.",
    isDecoy: true,
    color: "#4CAF50",
  },
  {
    id: "mystery_can",
    name: "Mystery Can",
    script: "ЧЕЧЕВИЦА",
    description: "A dented grey tin. The label fell off. It's written in marker...",
    isDecoy: true,
    color: "#9E9E9E",
    revealName: "Lentils",
    revealSpriteId: "lentil_reveal",
    pronunciation: "cheh-cheh-VEE-tsah",
    hints: [
      "Small. Round. Comes in brown, green, or red.",
      "It's a legume. Not beans, not peas. The other one.",
      "Soup. You make soup with it. I give up.",
    ],
  },
];

// === Level 9 items ===
export const level9Items: CollectibleItem[] = [
  // Targets
  {
    id: "tvorog_tub",
    name: "White Tub",
    script: "ТВОРОГ",
    description: "A green-labeled tub of something white and grainy.",
    isDecoy: false,
    color: "#e8f5e9",
    pronunciation: "TVOH-rog",
  },
  {
    id: "sosiski_pack",
    name: "Sausage Pack",
    script: "СОСИСКИ",
    description: "A vacuum-sealed package of thin sausages.",
    isDecoy: false,
    color: "#e08080",
    pronunciation: "sah-SEES-kee",
  },
  {
    id: "sveokla_beet",
    name: "Beetroot",
    script: "СВЁКЛА",
    description: "A dark purple-red beetroot with a stubby green top.",
    isDecoy: false,
    color: "#6B1F3A",
  },
  {
    id: "kefir_bottle",
    name: "Tall Bottle",
    script: "КЕФИР",
    description: "A tall bottle of some fermented drink.",
    isDecoy: false,
    color: "#E8F5E9",
  },
  // Decoys
  {
    id: "vodka_bottle",
    name: "Tall Frosted Bottle",
    script: "ВОДКА",
    description: "A frosted bottle with a red stripe label.",
    isDecoy: true,
    color: "#eeeeee",
  },
  {
    id: "bread_loaf",
    name: "Bread Loaf",
    script: "БАТОН",
    description: "A round loaf of golden bread.",
    isDecoy: true,
    color: "#c4a882",
  },
  {
    id: "sunflower_seeds",
    name: "Seed Bag",
    script: "СЕМЕЧКИ",
    description: "A rustling bag of sunflower seeds.",
    isDecoy: true,
    color: "#FFC107",
  },
  {
    id: "pickle_jar",
    name: "Pickle Jar",
    script: "ОГУРЦЫ",
    description: "A jar of pickled cucumbers.",
    isDecoy: true,
    color: "#4CAF50",
  },
  {
    id: "mystery_can",
    name: "Mystery Can",
    script: "НУТ",
    description: "A dented grey tin. The label fell off. It's written in marker...",
    isDecoy: true,
    color: "#9E9E9E",
    revealName: "Chickpeas",
    revealSpriteId: "chickpea_reveal",
    pronunciation: "NOOT",
    hints: [
      "Three letters. You can do three letters.",
      "Hummus. It's what hummus is made of.",
      "I hid this can behind a building for THREE LETTERS, Chad.",
    ],
  },
];
