import type { SkinConfig } from "../../types/skin";
import {
  babushkaSprite,
  marshrutkaSprite,
  potatoSprite,
  groundTile,
  platformTile,
  apartmentSprite,
  shopExteriorSprite,
  shopInteriorBgSprite,
  shopShelfSprite,
  shopkeeperSprite,
  shopkeeperBabushkaSprite,
  doorFrontSprite,
  doorBackSprite,
  doorLockedOverlay,
  exitSignSprite,
  interiorWallTile,
  interiorFloorTile,
  interiorCeilingTile,
  shelfWoodSprite,
  shelfMetalSprite,
  counterSprite,
} from "../../engine/sprites";
import { allLevels } from "./levels";

export const belarusSkin: SkinConfig = {
  id: "belarus",
  name: "Belarus",
  language: "Russian",
  mentorName: "Anya",
  mentorAvatar: "А",
  mentorColor: "#6C3483",
  messageColor: "#ce93d8",
  levels: allLevels,
  environment: {
    skyColor: "#1a1a2e",
    showStars: true,
    flagColors: ["#cc2222", "#33aa55"],
    groundTile,
    platformTile,
    gateSprite: apartmentSprite,
    gateLabel: "КВАРТИРА",
    npcSprite: babushkaSprite,
    vehicleSprite: marshrutkaSprite,
    sacredItemSprite: potatoSprite,
    scoldings: ["КУДА?!", "ОЙ!", "НЕ ЛЕЗЬ!", "БЕЗОБРАЗИЕ!", "ИДИ ОТСЮДА!"],
    headBounceCurse: "блять!",
    shopExteriorSprite,
    shopInteriorBg: shopInteriorBgSprite,
    shopShelfSprite,
    shopkeeperSprite,
    shopkeeperBabushkaSprite,
    doorFrontSprite,
    doorBackSprite,
    doorLockedOverlay,
    exitSignSprite,
    interiorWallTile,
    interiorFloorTile,
    interiorCeilingTile,
    shelfWoodSprite,
    shelfMetalSprite,
    counterSprite,
  },
  winMessage: "You survived grocery shopping in Belarus. ...I suppose you can stay.",
  sacredItemName: "The Sacred Potato",
  sacredItemLine: "The Sacred Potato is proud. Probably.",
  deathText: "УБИТ!",
  deathQuips: [
    "Good. Maybe now he'll stop.",
    "I told him about the buses.",
    "...he walked into it. Again.",
    "The marshrutka does not negotiate.",
    "This is why I didn't give him my real number.",
  ],
  wordsLearned: [
    { script: "СМЕТАНА", translation: "sour cream" },
    { script: "КЕФИР", translation: "kefir" },
    { script: "КОЛБАСА", translation: "sausage" },
    { script: "ПРОДУКТЫ", translation: "groceries" },
    { script: "ЧАЙ", translation: "tea" },
    { script: "МОЛОКО", translation: "milk" },
    { script: "САХАР", translation: "sugar" },
    { script: "РЫБА", translation: "fish" },
    { script: "МАСЛО", translation: "butter" },
    { script: "КАРТОШКА", translation: "potato" },
    { script: "ХЛЕБ", translation: "bread" },
    { script: "КОНФЕТА", translation: "candy" },
    { script: "СЫР", translation: "cheese" },
    { script: "ЯБЛОКО", translation: "apple" },
    { script: "ТАРЕЛКА", translation: "plate" },
    { script: "ЛОЖКА", translation: "spoon" },
    { script: "ЧАШКА", translation: "cup" },
    { script: "ЗАВТРАК", translation: "breakfast" },
    { script: "СЛИВКИ", translation: "cream" },
    { script: "ГРИБ", translation: "mushroom" },
  ],
};
